# Simple workflow for deploying static content to GitHub Pages
name: CD

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Prevent overlapping runs for GitHub Pages deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job for deploying static content
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './src' # Ensure that the "src" folder contains the static content to deploy

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
